### PR TITLE
Update task-force-1-2.md

### PR DESCRIPTION
**Pull request by mprah1**
Change website for Andrey

### CODE REVIEW

**Comment by notZaki** [comment]
I think the `email: ` part is needed before each member's email address but they got removed in the change. 
Could you please add them back?

**Comment by mprah1** [comment]
When “email: ” was listed, they emails didn’t appear on the webpage. Is there another suggestion?

**Comment by notZaki** [comment]
Oh, you're right, the email field isn't recognized. 
For now, add the `email: ` part before each address.

We'll have to change something else in the backend later for it to show up on the page.

**Comment by mprah1** [comment]
Thanks. They have been re-added.

**Comment by notZaki** [comment]
@mprah1 The emails should appear on the webpage now. Thanks for pointing that out.

**Comment by mprah1** [comment]
Thanks!

I have checked the webpage and the emails appear. Unrelated, it seems the line spacing is also very tight in the members section, so that the web address icons overlap with the next lines.

[cid:image001.png@01D6A6F5.DEA60970]

**Comment by notZaki** [comment]
@mprah1 
Thanks for pointing that out.
The spacing between the members has been slightly increased. 
The web address icon has also been removed---the member name now acts as the hyperlink.

**Comment by mprah1** [comment]
Thanks, looks great!


On Oct 20, 2020, at 4:02 PM, Zaki A. <notifications@github.com<mailto:notifications@github.com>> wrote:

ATTENTION: This email originated from a sender outside of MCW. Use caution when clicking on links or opening attachments.
________________________________

@mprah1<https://urldefense.com/v3/__https://github.com/mprah1__;!!H8mHWRdzp34!sV2mz_fYeJkm1MPL-HHhCLx7k23wl9Kb8rHjQ19melfH-3pLmdqDHQVIpkY0tg$>
Thanks for pointing that out.
The spacing between the members has been slightly increased.
The web address icon has also been removed---the member name now acts as the hyperlink.

**Pull request merged**
