### PR TITLE
added link to my personal page

### PR DESCRIPTION
**Pull request by fzoellne**

### CODE REVIEW

**Comment by fzoellne** [comment]
reopen the pull request

**Comment by fedorov** [comment]
So, for whatever reason, site build failed for your change ... the only guess I have is your use of "ö", but don't know for sure. I will investigate.

**Comment by fzoellne** [comment]
Oh I see, I thought since Simon has special character and it worked mine can be placed too, but if that’s a major problem oe is fine too ☺

Yours
Frank

----------------
adj. Prof. Dr. Frank Zoellner
Group Leader "Medical Imaging (MRI, CT, X-Ray) and Image Analysis“
Computer Assisted Clinical Medicine
Medical Faculty Mannheim
Heidelberg University
Theodor-Kutzer-Ufer 1-3
D-68167 Mannheim

Phone: +49 (0)621 3835117
Fax:   +49 (0)621 3835123
Email: Frank.Zoellner@MedMa.Uni-Heidelberg.de<mailto:Frank.Zoellner@MedMa.Uni-Heidelberg.de>
Web: http://www.umm.uni-heidelberg.de/inst/cbtm/ckm/

Von: Andrey Fedorov [mailto:notifications@github.com]
Gesendet: Mittwoch, 13. März 2019 15:32
An: OSIPI/osipi.github.io
Cc: Zoellner, Frank; State change
Betreff: Re: [OSIPI/osipi.github.io] added link to my personal page (#8)


So, for whatever reason, site build failed for your change ... the only guess I have is your use of "ö", but don't know for sure. I will investigate.

**Comment by fedorov** [comment]
No, it should not be. It is very strange - I changed it from umlaut to "oe", it built fine, and then again changed from "oe" to umlaut, and now it is working. Maybe there was some issue with the specific encoding of that character as you typed it on your computer. No idea! But the bottom line - it works now as expected, the page appears updated to me, and the build status also is reporting ok.

**Comment by fedorov** [comment]
So I emailed GitHub support to get to the bottom of this, and apparently, that failure was due to intermittent issue on GitHub side! What a coincidence!

**Pull request merged**
