### PR TITLE
Standardize data and template for taskforce pages

### PR DESCRIPTION
**Pull request by notZaki**
This is an attempt at extending what was done in #35 for taskforce 4.2.
All the taskforce pages should have a layout similar to tf 4.2.
[Preview is available here](https://notzaki.github.io/osipi.github.io/task-force-1-1/)

**Changes**

The data for each taskforce is placed in YAML files located in [`_data/tf`](https://github.com/notZaki/osipi.github.io/tree/627f2d840c9b13c63068d077fe923293d72766c0/_data/tf).
These files are used to generate the content in the taskforce pages.
The template for the taskforce page is in [`_includes/taskforce_content.md`](https://github.com/notZaki/osipi.github.io/blob/627f2d840c9b13c63068d077fe923293d72766c0/_includes/taskforce_content.md).

The main advantage of these changes is that editing the template in `taskforce_content.md` will update all of the taskforce pages, rather than having to manually go through the markdown file for each page and edit it by hand.

The main disadvantage is the added complexity, since the content for each taskforce page is now no longer self-contained in a single markdown file. 
The older system was also easier to use since each page looked like a document, whereas the new `taskforce_content.md` looks more like code and requires familiarity with Jekyll's templating engine.

**Other Notes** 

I didn't edit the page for taskforce 6.1 because it doesn't follow the same pattern as the other pages (it has two lists for members instead of one).

@HenkMutsaerts recently added details at the bottom of each taskforce page. I temporarily moved them up (with the aims) during development but they could be moved back to the bottom if desired.

### CODE REVIEW

**Comment by plaresmedima** [comment]
Hi Zaki, thanks for all your input and I agree it makes much more sense to organise it along these lines with all the task force information in one place. Much easier to maintain and update. 

I was just wondering whether it would be possible to allow just a little more customisation so it can also accomodate exceptions such as tf 6.1 that we need to structure differently. Also the naming of the leads - usually they will be lead and co-lead but in some cases we need them on more equal footing and have two co-leads. 

I like the idea of having a standard preamble for the taks forces with the current headings (aims, leads, status etc) but is it possible to allow for free text below that (as it was previously)? I don't to restrict the task forces too much in how they can structure the content.

**Comment by plaresmedima** [comment]
I would make these changes myself but unfortunately my codings skills are not up to that!

**Comment by HenkMutsaerts** [comment]
Now the header is gone in which I specified “This task force is part of aim …” -> as the description that is now in each task force is actually the overarching description of the aim of which the task force is part. I don’t think it matters much, I just wanted to avoid confusion

**Comment by plaresmedima** [comment]
Yes the text at the top will need a bit of rewording - not it is not quite clear as the overall aim is just copy-pasted with the specific aims of the TF. I will play around a bit and see if it can be clearer.

**Comment by notZaki** [comment]
@HenkMutsaerts 
Sorry, I missed the header part when making the changes. I'll try thinking of a way for adding it back if necessary.

@plaresmedima 
For TF 6.1, I can make changes to accommodate this taskforce, but an alternative could be to split it into multiple taskforces (one for each modality). Though I'm guessing the taskforce is the way it is for a reason?

I didn't know that the co/lead distinction was intentional. I'll try to fix that.

Free text can be added to the end of the taskforce's markdown file, and it will appear below everything else on the page.

**Comment by plaresmedima** [comment]
Thanks Zaki,

We have a lot of task forces already and it's becoming a bit difficult to
manage so I'd rather not create any more fragmentation at this point. If
there's a way it would be great to allow a little flexibility in how task
forces are structured.

Steven

-----------------------------------------------------------------------------------
Steven Sourbron
Chair in Medical Imaging Physics
Department of Infection, Immunity and Cardiovascular Disease
University of Sheffield
-----------------------------------------------------------------------------------

**Pull request merged**
