### PR TITLE
Updating the logo

### PR DESCRIPTION
**Pull request by notZaki**
**Changes**

- Added the newer logo to the main page
   + The CSS was updated to make the logo ok~ish at different sizes. The aggressive drop-shadow should make it stand out on a busy background. 
- Removed the logo from the events page
   + By default, the logo appears on any page with a header. This behaviour was  over-ridden by specifing a title.
   + The theme's `_layouts` could also be modified to disable this behaviour.
- Changed the colours---or rather, sucked out all the colours. The top-menu is now light-grey/red, and some elements like the 'Learn More' link on the main page went from red to purple. The drop-menu (that appears when hovering over 'Aims' on the top-menubar) also has a shadow behind it now. The links at the bottom of the page were changed from grey to green. 
   + This probably should've been placed in a separate PR, but I was playing with the colours on the same branch. I'll probably rebase this out.
- The favicon was not changed.

[A preview of the changes can be viewed here.](https://osipi.netlify.com/)

### CODE REVIEW

**Comment by fedorov** [comment]
Thank you @notZaki!

I looked at the preview, and I am wondering if the wide (horizontal) logo version would look better? Did you try that? It looks a bit too busy at the moment, since the height of the logo is close to the height of the image.

OSIPI_sml_w

**Comment by fedorov** [comment]
Also, you mentioned logo should appear on every page with a header, but this does not seem to be the case:

image

Just in case you did not notice it. It does not need to appear, if that is difficult - just letting you know.

**Comment by notZaki** [comment]
Good idea, I'll try the wider version.

Regarding the headers: I don't want the logo to appear in every page's header, but it's the theme's default behaviour to force the logo onto each header.
Most pages are not affected because they have `header: no` configured in their source file. 
The events page was the exception (that I'm aware of), so the logo was initially appearing on that page and was removed by specifying a header title.

**Comment by notZaki** [comment]
[Preview is updated with the wider logo.](https://osipi.netlify.com/)
Looks better than previous version to me.

**Comment by fedorov** [comment]
This looks very nice to me! I am going to merge this, and we can revise further if there is feedback from the group.

I greatly appreciate your work on this Zaki, thank you!!

**Comment by fedorov** [comment]
Oh, wait - it is still marked as draft - let me know when you feel it is ready!

**Comment by notZaki** [comment]
It should be good to go now.

**Pull request merged**
