### PR TITLE
Updates from TF3.1

### PR DESCRIPTION
**Pull request by lchenze**

### CODE REVIEW

**Comment by notZaki** [comment]
The changes can't be merged because of a conflict. Git is not sure if the following section should be included or deleted (it exists on the current site):
```
 - website: https://docs.google.com/spreadsheets/d/1pUUngtguEUKRKBwCI-nhgstDI23-pVVFQWYPjjzuuu0/edit?usp=sharing
    description: |
      Demo Phantom and DRO Inventory version 1.    
```

Would you like me to resolve this or do you want to resolve it yourself?

**Comment by lchenze** [comment]
Thank you!  I believe I resolved it by removing the previous website link.

**Comment by notZaki** [comment]
Great! 

Was this pull request meant to be closed? It hasn't been merged yet.

**Comment by lchenze** [comment]
Hello,

Sorry!  I’m clearly not skilled at this yet.  I intended to remove the conflicting code.  I would like the rest of it to be put in with the website – So yes I would like it to be merged.

Leah

**Review by notZaki — APPROVED** [review]

**Comment by notZaki** [comment]
No worries. The buttons are right next to each other, and it's a bit confusing because the one with the checkmark is usually the wrong one to press.

The changes have been merged and they're now live on the website.

**Pull request merged**
